# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-17 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
