# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-05 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.ImageField(blank=True, upload_to='album_images'),
        ),
    ]
