# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-06 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20190106_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_image',
        ),
    ]
