# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-16 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20190116_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
