# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-16 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_album_is_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 22, 31, 14, 310980)),
        ),
    ]
