# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-16 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20190116_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 22, 33, 2, 963248)),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 22, 33, 2, 940260)),
        ),
    ]
