# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-16 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20190117_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 1, 3, 12, 691867)),
        ),
        migrations.AlterField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 1, 3, 12, 692866)),
        ),
    ]
