# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-17 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20190118_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_name',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(default='ac', max_length=50),
            preserve_default=False,
        ),
    ]
