# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-18 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_auto_20190118_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='onion'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
